/** Generated — all ISO countries with E.164 codes (restcountries.com). Do not edit by hand; re-run scripts/generate-phone-countries.mjs */
export const PHONE_COUNTRIES_DATA = [
  { id: "id", dial: "+62", flag: "🇮🇩", countryName: "Indonesia", label: "Indonesia (+62)" },
  { id: "af", dial: "+93", flag: "🇦🇫", countryName: "Afghanistan", label: "Afghanistan (+93)" },
  { id: "ax", dial: "+35818", flag: "🇦🇽", countryName: "Åland Islands", label: "Åland Islands (+35818)" },
  { id: "al", dial: "+355", flag: "🇦🇱", countryName: "Albania", label: "Albania (+355)" },
  { id: "dz", dial: "+213", flag: "🇩🇿", countryName: "Algeria", label: "Algeria (+213)" },
  { id: "as", dial: "+1684", flag: "🇦🇸", countryName: "American Samoa", label: "American Samoa (+1684)" },
  { id: "ad", dial: "+376", flag: "🇦🇩", countryName: "Andorra", label: "Andorra (+376)" },
  { id: "ao", dial: "+244", flag: "🇦🇴", countryName: "Angola", label: "Angola (+244)" },
  { id: "ai", dial: "+1264", flag: "🇦🇮", countryName: "Anguilla", label: "Anguilla (+1264)" },
  { id: "ag", dial: "+1268", flag: "🇦🇬", countryName: "Antigua and Barbuda", label: "Antigua and Barbuda (+1268)" },
  { id: "ar", dial: "+54", flag: "🇦🇷", countryName: "Argentina", label: "Argentina (+54)" },
  { id: "am", dial: "+374", flag: "🇦🇲", countryName: "Armenia", label: "Armenia (+374)" },
  { id: "aw", dial: "+297", flag: "🇦🇼", countryName: "Aruba", label: "Aruba (+297)" },
  { id: "au", dial: "+61", flag: "🇦🇺", countryName: "Australia", label: "Australia (+61)" },
  { id: "at", dial: "+43", flag: "🇦🇹", countryName: "Austria", label: "Austria (+43)" },
  { id: "az", dial: "+994", flag: "🇦🇿", countryName: "Azerbaijan", label: "Azerbaijan (+994)" },
  { id: "bs", dial: "+1242", flag: "🇧🇸", countryName: "Bahamas", label: "Bahamas (+1242)" },
  { id: "bh", dial: "+973", flag: "🇧🇭", countryName: "Bahrain", label: "Bahrain (+973)" },
  { id: "bd", dial: "+880", flag: "🇧🇩", countryName: "Bangladesh", label: "Bangladesh (+880)" },
  { id: "bb", dial: "+1246", flag: "🇧🇧", countryName: "Barbados", label: "Barbados (+1246)" },
  { id: "by", dial: "+375", flag: "🇧🇾", countryName: "Belarus", label: "Belarus (+375)" },
  { id: "be", dial: "+32", flag: "🇧🇪", countryName: "Belgium", label: "Belgium (+32)" },
  { id: "bz", dial: "+501", flag: "🇧🇿", countryName: "Belize", label: "Belize (+501)" },
  { id: "bj", dial: "+229", flag: "🇧🇯", countryName: "Benin", label: "Benin (+229)" },
  { id: "bm", dial: "+1441", flag: "🇧🇲", countryName: "Bermuda", label: "Bermuda (+1441)" },
  { id: "bt", dial: "+975", flag: "🇧🇹", countryName: "Bhutan", label: "Bhutan (+975)" },
  { id: "bo", dial: "+591", flag: "🇧🇴", countryName: "Bolivia", label: "Bolivia (+591)" },
  { id: "ba", dial: "+387", flag: "🇧🇦", countryName: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina (+387)" },
  { id: "bw", dial: "+267", flag: "🇧🇼", countryName: "Botswana", label: "Botswana (+267)" },
  { id: "bv", dial: "+47", flag: "🇧🇻", countryName: "Bouvet Island", label: "Bouvet Island (+47)" },
  { id: "br", dial: "+55", flag: "🇧🇷", countryName: "Brazil", label: "Brazil (+55)" },
  { id: "io", dial: "+246", flag: "🇮🇴", countryName: "British Indian Ocean Territory", label: "British Indian Ocean Territory (+246)" },
  { id: "vg", dial: "+1284", flag: "🇻🇬", countryName: "British Virgin Islands", label: "British Virgin Islands (+1284)" },
  { id: "bn", dial: "+673", flag: "🇧🇳", countryName: "Brunei", label: "Brunei (+673)" },
  { id: "bg", dial: "+359", flag: "🇧🇬", countryName: "Bulgaria", label: "Bulgaria (+359)" },
  { id: "bf", dial: "+226", flag: "🇧🇫", countryName: "Burkina Faso", label: "Burkina Faso (+226)" },
  { id: "bi", dial: "+257", flag: "🇧🇮", countryName: "Burundi", label: "Burundi (+257)" },
  { id: "kh", dial: "+855", flag: "🇰🇭", countryName: "Cambodia", label: "Cambodia (+855)" },
  { id: "cm", dial: "+237", flag: "🇨🇲", countryName: "Cameroon", label: "Cameroon (+237)" },
  { id: "ca", dial: "+1", flag: "🇨🇦", countryName: "Canada", label: "Canada (+1)" },
  { id: "cv", dial: "+238", flag: "🇨🇻", countryName: "Cape Verde", label: "Cape Verde (+238)" },
  { id: "bq", dial: "+599", flag: "🇧🇶", countryName: "Caribbean Netherlands", label: "Caribbean Netherlands (+599)" },
  { id: "ky", dial: "+1345", flag: "🇰🇾", countryName: "Cayman Islands", label: "Cayman Islands (+1345)" },
  { id: "cf", dial: "+236", flag: "🇨🇫", countryName: "Central African Republic", label: "Central African Republic (+236)" },
  { id: "td", dial: "+235", flag: "🇹🇩", countryName: "Chad", label: "Chad (+235)" },
  { id: "cl", dial: "+56", flag: "🇨🇱", countryName: "Chile", label: "Chile (+56)" },
  { id: "cn", dial: "+86", flag: "🇨🇳", countryName: "China", label: "China (+86)" },
  { id: "cx", dial: "+61", flag: "🇨🇽", countryName: "Christmas Island", label: "Christmas Island (+61)" },
  { id: "cc", dial: "+61", flag: "🇨🇨", countryName: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands (+61)" },
  { id: "co", dial: "+57", flag: "🇨🇴", countryName: "Colombia", label: "Colombia (+57)" },
  { id: "km", dial: "+269", flag: "🇰🇲", countryName: "Comoros", label: "Comoros (+269)" },
  { id: "ck", dial: "+682", flag: "🇨🇰", countryName: "Cook Islands", label: "Cook Islands (+682)" },
  { id: "cr", dial: "+506", flag: "🇨🇷", countryName: "Costa Rica", label: "Costa Rica (+506)" },
  { id: "hr", dial: "+385", flag: "🇭🇷", countryName: "Croatia", label: "Croatia (+385)" },
  { id: "cu", dial: "+53", flag: "🇨🇺", countryName: "Cuba", label: "Cuba (+53)" },
  { id: "cw", dial: "+599", flag: "🇨🇼", countryName: "Curaçao", label: "Curaçao (+599)" },
  { id: "cy", dial: "+357", flag: "🇨🇾", countryName: "Cyprus", label: "Cyprus (+357)" },
  { id: "cz", dial: "+420", flag: "🇨🇿", countryName: "Czechia", label: "Czechia (+420)" },
  { id: "dk", dial: "+45", flag: "🇩🇰", countryName: "Denmark", label: "Denmark (+45)" },
  { id: "dj", dial: "+253", flag: "🇩🇯", countryName: "Djibouti", label: "Djibouti (+253)" },
  { id: "dm", dial: "+1767", flag: "🇩🇲", countryName: "Dominica", label: "Dominica (+1767)" },
  { id: "do", dial: "+1809", flag: "🇩🇴", countryName: "Dominican Republic", label: "Dominican Republic (+1809)" },
  { id: "cd", dial: "+243", flag: "🇨🇩", countryName: "DR Congo", label: "DR Congo (+243)" },
  { id: "ec", dial: "+593", flag: "🇪🇨", countryName: "Ecuador", label: "Ecuador (+593)" },
  { id: "eg", dial: "+20", flag: "🇪🇬", countryName: "Egypt", label: "Egypt (+20)" },
  { id: "sv", dial: "+503", flag: "🇸🇻", countryName: "El Salvador", label: "El Salvador (+503)" },
  { id: "gq", dial: "+240", flag: "🇬🇶", countryName: "Equatorial Guinea", label: "Equatorial Guinea (+240)" },
  { id: "er", dial: "+291", flag: "🇪🇷", countryName: "Eritrea", label: "Eritrea (+291)" },
  { id: "ee", dial: "+372", flag: "🇪🇪", countryName: "Estonia", label: "Estonia (+372)" },
  { id: "sz", dial: "+268", flag: "🇸🇿", countryName: "Eswatini", label: "Eswatini (+268)" },
  { id: "et", dial: "+251", flag: "🇪🇹", countryName: "Ethiopia", label: "Ethiopia (+251)" },
  { id: "fk", dial: "+500", flag: "🇫🇰", countryName: "Falkland Islands", label: "Falkland Islands (+500)" },
  { id: "fo", dial: "+298", flag: "🇫🇴", countryName: "Faroe Islands", label: "Faroe Islands (+298)" },
  { id: "fj", dial: "+679", flag: "🇫🇯", countryName: "Fiji", label: "Fiji (+679)" },
  { id: "fi", dial: "+358", flag: "🇫🇮", countryName: "Finland", label: "Finland (+358)" },
  { id: "fr", dial: "+33", flag: "🇫🇷", countryName: "France", label: "France (+33)" },
  { id: "gf", dial: "+594", flag: "🇬🇫", countryName: "French Guiana", label: "French Guiana (+594)" },
  { id: "pf", dial: "+689", flag: "🇵🇫", countryName: "French Polynesia", label: "French Polynesia (+689)" },
  { id: "tf", dial: "+262", flag: "🇹🇫", countryName: "French Southern and Antarctic Lands", label: "French Southern and Antarctic Lands (+262)" },
  { id: "ga", dial: "+241", flag: "🇬🇦", countryName: "Gabon", label: "Gabon (+241)" },
  { id: "gm", dial: "+220", flag: "🇬🇲", countryName: "Gambia", label: "Gambia (+220)" },
  { id: "ge", dial: "+995", flag: "🇬🇪", countryName: "Georgia", label: "Georgia (+995)" },
  { id: "de", dial: "+49", flag: "🇩🇪", countryName: "Germany", label: "Germany (+49)" },
  { id: "gh", dial: "+233", flag: "🇬🇭", countryName: "Ghana", label: "Ghana (+233)" },
  { id: "gi", dial: "+350", flag: "🇬🇮", countryName: "Gibraltar", label: "Gibraltar (+350)" },
  { id: "gr", dial: "+30", flag: "🇬🇷", countryName: "Greece", label: "Greece (+30)" },
  { id: "gl", dial: "+299", flag: "🇬🇱", countryName: "Greenland", label: "Greenland (+299)" },
  { id: "gd", dial: "+1473", flag: "🇬🇩", countryName: "Grenada", label: "Grenada (+1473)" },
  { id: "gp", dial: "+590", flag: "🇬🇵", countryName: "Guadeloupe", label: "Guadeloupe (+590)" },
  { id: "gu", dial: "+1671", flag: "🇬🇺", countryName: "Guam", label: "Guam (+1671)" },
  { id: "gt", dial: "+502", flag: "🇬🇹", countryName: "Guatemala", label: "Guatemala (+502)" },
  { id: "gg", dial: "+44", flag: "🇬🇬", countryName: "Guernsey", label: "Guernsey (+44)" },
  { id: "gn", dial: "+224", flag: "🇬🇳", countryName: "Guinea", label: "Guinea (+224)" },
  { id: "gw", dial: "+245", flag: "🇬🇼", countryName: "Guinea-Bissau", label: "Guinea-Bissau (+245)" },
  { id: "gy", dial: "+592", flag: "🇬🇾", countryName: "Guyana", label: "Guyana (+592)" },
  { id: "ht", dial: "+509", flag: "🇭🇹", countryName: "Haiti", label: "Haiti (+509)" },
  { id: "hn", dial: "+504", flag: "🇭🇳", countryName: "Honduras", label: "Honduras (+504)" },
  { id: "hk", dial: "+852", flag: "🇭🇰", countryName: "Hong Kong", label: "Hong Kong (+852)" },
  { id: "hu", dial: "+36", flag: "🇭🇺", countryName: "Hungary", label: "Hungary (+36)" },
  { id: "is", dial: "+354", flag: "🇮🇸", countryName: "Iceland", label: "Iceland (+354)" },
  { id: "in", dial: "+91", flag: "🇮🇳", countryName: "India", label: "India (+91)" },
  { id: "ir", dial: "+98", flag: "🇮🇷", countryName: "Iran", label: "Iran (+98)" },
  { id: "iq", dial: "+964", flag: "🇮🇶", countryName: "Iraq", label: "Iraq (+964)" },
  { id: "ie", dial: "+353", flag: "🇮🇪", countryName: "Ireland", label: "Ireland (+353)" },
  { id: "im", dial: "+44", flag: "🇮🇲", countryName: "Isle of Man", label: "Isle of Man (+44)" },
  { id: "il", dial: "+972", flag: "🇮🇱", countryName: "Israel", label: "Israel (+972)" },
  { id: "it", dial: "+39", flag: "🇮🇹", countryName: "Italy", label: "Italy (+39)" },
  { id: "ci", dial: "+225", flag: "🇨🇮", countryName: "Ivory Coast", label: "Ivory Coast (+225)" },
  { id: "jm", dial: "+1876", flag: "🇯🇲", countryName: "Jamaica", label: "Jamaica (+1876)" },
  { id: "jp", dial: "+81", flag: "🇯🇵", countryName: "Japan", label: "Japan (+81)" },
  { id: "je", dial: "+44", flag: "🇯🇪", countryName: "Jersey", label: "Jersey (+44)" },
  { id: "jo", dial: "+962", flag: "🇯🇴", countryName: "Jordan", label: "Jordan (+962)" },
  { id: "kz", dial: "+76", flag: "🇰🇿", countryName: "Kazakhstan", label: "Kazakhstan (+76)" },
  { id: "ke", dial: "+254", flag: "🇰🇪", countryName: "Kenya", label: "Kenya (+254)" },
  { id: "ki", dial: "+686", flag: "🇰🇮", countryName: "Kiribati", label: "Kiribati (+686)" },
  { id: "xk", dial: "+383", flag: "🇽🇰", countryName: "Kosovo", label: "Kosovo (+383)" },
  { id: "kw", dial: "+965", flag: "🇰🇼", countryName: "Kuwait", label: "Kuwait (+965)" },
  { id: "kg", dial: "+996", flag: "🇰🇬", countryName: "Kyrgyzstan", label: "Kyrgyzstan (+996)" },
  { id: "la", dial: "+856", flag: "🇱🇦", countryName: "Laos", label: "Laos (+856)" },
  { id: "lv", dial: "+371", flag: "🇱🇻", countryName: "Latvia", label: "Latvia (+371)" },
  { id: "lb", dial: "+961", flag: "🇱🇧", countryName: "Lebanon", label: "Lebanon (+961)" },
  { id: "ls", dial: "+266", flag: "🇱🇸", countryName: "Lesotho", label: "Lesotho (+266)" },
  { id: "lr", dial: "+231", flag: "🇱🇷", countryName: "Liberia", label: "Liberia (+231)" },
  { id: "ly", dial: "+218", flag: "🇱🇾", countryName: "Libya", label: "Libya (+218)" },
  { id: "li", dial: "+423", flag: "🇱🇮", countryName: "Liechtenstein", label: "Liechtenstein (+423)" },
  { id: "lt", dial: "+370", flag: "🇱🇹", countryName: "Lithuania", label: "Lithuania (+370)" },
  { id: "lu", dial: "+352", flag: "🇱🇺", countryName: "Luxembourg", label: "Luxembourg (+352)" },
  { id: "mo", dial: "+853", flag: "🇲🇴", countryName: "Macau", label: "Macau (+853)" },
  { id: "mg", dial: "+261", flag: "🇲🇬", countryName: "Madagascar", label: "Madagascar (+261)" },
  { id: "mw", dial: "+265", flag: "🇲🇼", countryName: "Malawi", label: "Malawi (+265)" },
  { id: "my", dial: "+60", flag: "🇲🇾", countryName: "Malaysia", label: "Malaysia (+60)" },
  { id: "mv", dial: "+960", flag: "🇲🇻", countryName: "Maldives", label: "Maldives (+960)" },
  { id: "ml", dial: "+223", flag: "🇲🇱", countryName: "Mali", label: "Mali (+223)" },
  { id: "mt", dial: "+356", flag: "🇲🇹", countryName: "Malta", label: "Malta (+356)" },
  { id: "mh", dial: "+692", flag: "🇲🇭", countryName: "Marshall Islands", label: "Marshall Islands (+692)" },
  { id: "mq", dial: "+596", flag: "🇲🇶", countryName: "Martinique", label: "Martinique (+596)" },
  { id: "mr", dial: "+222", flag: "🇲🇷", countryName: "Mauritania", label: "Mauritania (+222)" },
  { id: "mu", dial: "+230", flag: "🇲🇺", countryName: "Mauritius", label: "Mauritius (+230)" },
  { id: "yt", dial: "+262", flag: "🇾🇹", countryName: "Mayotte", label: "Mayotte (+262)" },
  { id: "mx", dial: "+52", flag: "🇲🇽", countryName: "Mexico", label: "Mexico (+52)" },
  { id: "fm", dial: "+691", flag: "🇫🇲", countryName: "Micronesia", label: "Micronesia (+691)" },
  { id: "md", dial: "+373", flag: "🇲🇩", countryName: "Moldova", label: "Moldova (+373)" },
  { id: "mc", dial: "+377", flag: "🇲🇨", countryName: "Monaco", label: "Monaco (+377)" },
  { id: "mn", dial: "+976", flag: "🇲🇳", countryName: "Mongolia", label: "Mongolia (+976)" },
  { id: "me", dial: "+382", flag: "🇲🇪", countryName: "Montenegro", label: "Montenegro (+382)" },
  { id: "ms", dial: "+1664", flag: "🇲🇸", countryName: "Montserrat", label: "Montserrat (+1664)" },
  { id: "ma", dial: "+212", flag: "🇲🇦", countryName: "Morocco", label: "Morocco (+212)" },
  { id: "mz", dial: "+258", flag: "🇲🇿", countryName: "Mozambique", label: "Mozambique (+258)" },
  { id: "mm", dial: "+95", flag: "🇲🇲", countryName: "Myanmar", label: "Myanmar (+95)" },
  { id: "na", dial: "+264", flag: "🇳🇦", countryName: "Namibia", label: "Namibia (+264)" },
  { id: "nr", dial: "+674", flag: "🇳🇷", countryName: "Nauru", label: "Nauru (+674)" },
  { id: "np", dial: "+977", flag: "🇳🇵", countryName: "Nepal", label: "Nepal (+977)" },
  { id: "nl", dial: "+31", flag: "🇳🇱", countryName: "Netherlands", label: "Netherlands (+31)" },
  { id: "nc", dial: "+687", flag: "🇳🇨", countryName: "New Caledonia", label: "New Caledonia (+687)" },
  { id: "nz", dial: "+64", flag: "🇳🇿", countryName: "New Zealand", label: "New Zealand (+64)" },
  { id: "ni", dial: "+505", flag: "🇳🇮", countryName: "Nicaragua", label: "Nicaragua (+505)" },
  { id: "ne", dial: "+227", flag: "🇳🇪", countryName: "Niger", label: "Niger (+227)" },
  { id: "ng", dial: "+234", flag: "🇳🇬", countryName: "Nigeria", label: "Nigeria (+234)" },
  { id: "nu", dial: "+683", flag: "🇳🇺", countryName: "Niue", label: "Niue (+683)" },
  { id: "nf", dial: "+672", flag: "🇳🇫", countryName: "Norfolk Island", label: "Norfolk Island (+672)" },
  { id: "kp", dial: "+850", flag: "🇰🇵", countryName: "North Korea", label: "North Korea (+850)" },
  { id: "mk", dial: "+389", flag: "🇲🇰", countryName: "North Macedonia", label: "North Macedonia (+389)" },
  { id: "mp", dial: "+1670", flag: "🇲🇵", countryName: "Northern Mariana Islands", label: "Northern Mariana Islands (+1670)" },
  { id: "no", dial: "+47", flag: "🇳🇴", countryName: "Norway", label: "Norway (+47)" },
  { id: "om", dial: "+968", flag: "🇴🇲", countryName: "Oman", label: "Oman (+968)" },
  { id: "pk", dial: "+92", flag: "🇵🇰", countryName: "Pakistan", label: "Pakistan (+92)" },
  { id: "pw", dial: "+680", flag: "🇵🇼", countryName: "Palau", label: "Palau (+680)" },
  { id: "ps", dial: "+970", flag: "🇵🇸", countryName: "Palestine", label: "Palestine (+970)" },
  { id: "pa", dial: "+507", flag: "🇵🇦", countryName: "Panama", label: "Panama (+507)" },
  { id: "pg", dial: "+675", flag: "🇵🇬", countryName: "Papua New Guinea", label: "Papua New Guinea (+675)" },
  { id: "py", dial: "+595", flag: "🇵🇾", countryName: "Paraguay", label: "Paraguay (+595)" },
  { id: "pe", dial: "+51", flag: "🇵🇪", countryName: "Peru", label: "Peru (+51)" },
  { id: "ph", dial: "+63", flag: "🇵🇭", countryName: "Philippines", label: "Philippines (+63)" },
  { id: "pn", dial: "+64", flag: "🇵🇳", countryName: "Pitcairn Islands", label: "Pitcairn Islands (+64)" },
  { id: "pl", dial: "+48", flag: "🇵🇱", countryName: "Poland", label: "Poland (+48)" },
  { id: "pt", dial: "+351", flag: "🇵🇹", countryName: "Portugal", label: "Portugal (+351)" },
  { id: "pr", dial: "+1787", flag: "🇵🇷", countryName: "Puerto Rico", label: "Puerto Rico (+1787)" },
  { id: "qa", dial: "+974", flag: "🇶🇦", countryName: "Qatar", label: "Qatar (+974)" },
  { id: "cg", dial: "+242", flag: "🇨🇬", countryName: "Republic of the Congo", label: "Republic of the Congo (+242)" },
  { id: "re", dial: "+262", flag: "🇷🇪", countryName: "Réunion", label: "Réunion (+262)" },
  { id: "ro", dial: "+40", flag: "🇷🇴", countryName: "Romania", label: "Romania (+40)" },
  { id: "ru", dial: "+73", flag: "🇷🇺", countryName: "Russia", label: "Russia (+73)" },
  { id: "rw", dial: "+250", flag: "🇷🇼", countryName: "Rwanda", label: "Rwanda (+250)" },
  { id: "bl", dial: "+590", flag: "🇧🇱", countryName: "Saint Barthélemy", label: "Saint Barthélemy (+590)" },
  { id: "sh", dial: "+290", flag: "🇸🇭", countryName: "Saint Helena, Ascension and Tristan da Cunha", label: "Saint Helena, Ascension and Tristan da Cunha (+290)" },
  { id: "kn", dial: "+1869", flag: "🇰🇳", countryName: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis (+1869)" },
  { id: "lc", dial: "+1758", flag: "🇱🇨", countryName: "Saint Lucia", label: "Saint Lucia (+1758)" },
  { id: "mf", dial: "+590", flag: "🇲🇫", countryName: "Saint Martin", label: "Saint Martin (+590)" },
  { id: "pm", dial: "+508", flag: "🇵🇲", countryName: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon (+508)" },
  { id: "vc", dial: "+1784", flag: "🇻🇨", countryName: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines (+1784)" },
  { id: "ws", dial: "+685", flag: "🇼🇸", countryName: "Samoa", label: "Samoa (+685)" },
  { id: "sm", dial: "+378", flag: "🇸🇲", countryName: "San Marino", label: "San Marino (+378)" },
  { id: "st", dial: "+239", flag: "🇸🇹", countryName: "São Tomé and Príncipe", label: "São Tomé and Príncipe (+239)" },
  { id: "sa", dial: "+966", flag: "🇸🇦", countryName: "Saudi Arabia", label: "Saudi Arabia (+966)" },
  { id: "sn", dial: "+221", flag: "🇸🇳", countryName: "Senegal", label: "Senegal (+221)" },
  { id: "rs", dial: "+381", flag: "🇷🇸", countryName: "Serbia", label: "Serbia (+381)" },
  { id: "sc", dial: "+248", flag: "🇸🇨", countryName: "Seychelles", label: "Seychelles (+248)" },
  { id: "sl", dial: "+232", flag: "🇸🇱", countryName: "Sierra Leone", label: "Sierra Leone (+232)" },
  { id: "sg", dial: "+65", flag: "🇸🇬", countryName: "Singapore", label: "Singapore (+65)" },
  { id: "sx", dial: "+1721", flag: "🇸🇽", countryName: "Sint Maarten", label: "Sint Maarten (+1721)" },
  { id: "sk", dial: "+421", flag: "🇸🇰", countryName: "Slovakia", label: "Slovakia (+421)" },
  { id: "si", dial: "+386", flag: "🇸🇮", countryName: "Slovenia", label: "Slovenia (+386)" },
  { id: "sb", dial: "+677", flag: "🇸🇧", countryName: "Solomon Islands", label: "Solomon Islands (+677)" },
  { id: "so", dial: "+252", flag: "🇸🇴", countryName: "Somalia", label: "Somalia (+252)" },
  { id: "za", dial: "+27", flag: "🇿🇦", countryName: "South Africa", label: "South Africa (+27)" },
  { id: "gs", dial: "+500", flag: "🇬🇸", countryName: "South Georgia", label: "South Georgia (+500)" },
  { id: "kr", dial: "+82", flag: "🇰🇷", countryName: "South Korea", label: "South Korea (+82)" },
  { id: "ss", dial: "+211", flag: "🇸🇸", countryName: "South Sudan", label: "South Sudan (+211)" },
  { id: "es", dial: "+34", flag: "🇪🇸", countryName: "Spain", label: "Spain (+34)" },
  { id: "lk", dial: "+94", flag: "🇱🇰", countryName: "Sri Lanka", label: "Sri Lanka (+94)" },
  { id: "sd", dial: "+249", flag: "🇸🇩", countryName: "Sudan", label: "Sudan (+249)" },
  { id: "sr", dial: "+597", flag: "🇸🇷", countryName: "Suriname", label: "Suriname (+597)" },
  { id: "sj", dial: "+4779", flag: "🇸🇯", countryName: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen (+4779)" },
  { id: "se", dial: "+46", flag: "🇸🇪", countryName: "Sweden", label: "Sweden (+46)" },
  { id: "ch", dial: "+41", flag: "🇨🇭", countryName: "Switzerland", label: "Switzerland (+41)" },
  { id: "sy", dial: "+963", flag: "🇸🇾", countryName: "Syria", label: "Syria (+963)" },
  { id: "tw", dial: "+886", flag: "🇹🇼", countryName: "Taiwan", label: "Taiwan (+886)" },
  { id: "tj", dial: "+992", flag: "🇹🇯", countryName: "Tajikistan", label: "Tajikistan (+992)" },
  { id: "tz", dial: "+255", flag: "🇹🇿", countryName: "Tanzania", label: "Tanzania (+255)" },
  { id: "th", dial: "+66", flag: "🇹🇭", countryName: "Thailand", label: "Thailand (+66)" },
  { id: "tl", dial: "+670", flag: "🇹🇱", countryName: "Timor-Leste", label: "Timor-Leste (+670)" },
  { id: "tg", dial: "+228", flag: "🇹🇬", countryName: "Togo", label: "Togo (+228)" },
  { id: "tk", dial: "+690", flag: "🇹🇰", countryName: "Tokelau", label: "Tokelau (+690)" },
  { id: "to", dial: "+676", flag: "🇹🇴", countryName: "Tonga", label: "Tonga (+676)" },
  { id: "tt", dial: "+1868", flag: "🇹🇹", countryName: "Trinidad and Tobago", label: "Trinidad and Tobago (+1868)" },
  { id: "tn", dial: "+216", flag: "🇹🇳", countryName: "Tunisia", label: "Tunisia (+216)" },
  { id: "tr", dial: "+90", flag: "🇹🇷", countryName: "Turkey", label: "Turkey (+90)" },
  { id: "tm", dial: "+993", flag: "🇹🇲", countryName: "Turkmenistan", label: "Turkmenistan (+993)" },
  { id: "tc", dial: "+1649", flag: "🇹🇨", countryName: "Turks and Caicos Islands", label: "Turks and Caicos Islands (+1649)" },
  { id: "tv", dial: "+688", flag: "🇹🇻", countryName: "Tuvalu", label: "Tuvalu (+688)" },
  { id: "ug", dial: "+256", flag: "🇺🇬", countryName: "Uganda", label: "Uganda (+256)" },
  { id: "ua", dial: "+380", flag: "🇺🇦", countryName: "Ukraine", label: "Ukraine (+380)" },
  { id: "ae", dial: "+971", flag: "🇦🇪", countryName: "United Arab Emirates", label: "United Arab Emirates (+971)" },
  { id: "gb", dial: "+44", flag: "🇬🇧", countryName: "United Kingdom", label: "United Kingdom (+44)" },
  { id: "us", dial: "+1201", flag: "🇺🇸", countryName: "United States", label: "United States (+1201)" },
  { id: "um", dial: "+268", flag: "🇺🇲", countryName: "United States Minor Outlying Islands", label: "United States Minor Outlying Islands (+268)" },
  { id: "vi", dial: "+1340", flag: "🇻🇮", countryName: "United States Virgin Islands", label: "United States Virgin Islands (+1340)" },
  { id: "uy", dial: "+598", flag: "🇺🇾", countryName: "Uruguay", label: "Uruguay (+598)" },
  { id: "uz", dial: "+998", flag: "🇺🇿", countryName: "Uzbekistan", label: "Uzbekistan (+998)" },
  { id: "vu", dial: "+678", flag: "🇻🇺", countryName: "Vanuatu", label: "Vanuatu (+678)" },
  { id: "va", dial: "+3906698", flag: "🇻🇦", countryName: "Vatican City", label: "Vatican City (+3906698)" },
  { id: "ve", dial: "+58", flag: "🇻🇪", countryName: "Venezuela", label: "Venezuela (+58)" },
  { id: "vn", dial: "+84", flag: "🇻🇳", countryName: "Vietnam", label: "Vietnam (+84)" },
  { id: "wf", dial: "+681", flag: "🇼🇫", countryName: "Wallis and Futuna", label: "Wallis and Futuna (+681)" },
  { id: "eh", dial: "+2125288", flag: "🇪🇭", countryName: "Western Sahara", label: "Western Sahara (+2125288)" },
  { id: "ye", dial: "+967", flag: "🇾🇪", countryName: "Yemen", label: "Yemen (+967)" },
  { id: "zm", dial: "+260", flag: "🇿🇲", countryName: "Zambia", label: "Zambia (+260)" },
  { id: "zw", dial: "+263", flag: "🇿🇼", countryName: "Zimbabwe", label: "Zimbabwe (+263)" },
] as const;
export type PhoneCountry = (typeof PHONE_COUNTRIES_DATA)[number];
